version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio_tc:
    image: minio/minio
    container_name: minio_tc
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_KMS_SECRET_KEY: my-minio-key:YWRtaW4xMjNhZG1pbjEyM2FkbWluMTIzYWRtaW4xMjM=
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - PYTHONPATH=/opt/project
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/project:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dbt:/usr/app
    working_dir: /opt/project
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - minio_tc
    command: ["bash","-c","exec airflow standalone"]

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.4
    container_name: dbt
    volumes:
      - ./dbt:/usr/app
      - ./profiles:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    depends_on:
      - postgres

volumes:
  pg_data:
  minio_data:
